dark_theme:
  type: bool
  default: false
  description:
    en: 'Select to use with Dark Color Palettes'
large_avatar:
  type: bool
  default: false
  description:
    en: 'Select to use large avatars (90px vs 45px) on screens > 630px'
reminder_message: 
  type: bool
  default: false
  description:
    en: 'Select to show dismissible reminder message below header to use in Desktop View. Message sets a cookie when dismissed.'
message_color: 
  type: string
  default: "#FFF"
  description:
    en: 'Text color of the message. Default is White. The Background color is the Danger color from your palette'
